package Primitivas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;


public class PizarraC extends javax.swing.JFrame {

    /**
     * Creates new form PizarraC
     */
    Point p1, p2, p3,p4;
    boolean bDibujar, bDibujar2;

    Raster raster;
    int op;
    boolean firstTime = true;    

    public PizarraC() {
        initComponents();
        p1 = new Point();
        p2 = new Point();
        p3 = new Point();
        bDibujar = bDibujar2 = false;
        this.setMaximumSize(new Dimension(640, 480));
        this.setMinimumSize(new Dimension(640, 480));
        raster = new Raster(640, 480);
        this.setLocationRelativeTo(null);
        //op.setLocation(this.getX() - op.getWidth() - 15, this.getY());
        this.getContentPane().setBackground(Color.white);      
    }

    public void lineFast(int x0, int y0, int x1, int y1, Color color) {
        int pix = color.getRGB();
        int dy = y1 - y0;
        int dx = x1 - x0;
        int stepx, stepy;
        if (dy < 0) {
            dy = -dy;
            stepy = -raster.width;
        } else {
            stepy = raster.width;
        }
        if (dx < 0) {
            dx = -dx;
            stepx = -1;
        } else {
            stepx = 1;
        }
        dy <<= 1;
        dx <<= 1;
        y0 *= raster.width;
        y1 *= raster.width;
        raster.pixel[x0 + y0] = pix;
        if (dx > dy) {
            int fraction = dy - (dx >> 1);
            while (x0 != x1) {
                if (fraction >= 0) {
                    y0 += stepy;
                    fraction -= dx;
                }
                x0 += stepx;
                fraction += dy;
                raster.pixel[x0 + y0] = pix;
            }
        } else {
            int fraction = dx - (dy >> 1);
            while (y0 != y1) {
                if (fraction >= 0) {
                    x0 += stepx;
                    fraction -= dy;
                }
                y0 += stepy;
                fraction += dx;
                raster.pixel[x0 + y0] = pix;
            }
        }
    }

    void PlotPoint(Graphics g, int xc, int yc, int x, int y) {
        g.setColor(Color.red);
        g.drawRect(xc + x, yc + y, 1, 1);
        g.drawRect(xc - x, yc + y, 1, 1);
        g.drawRect(xc + x, yc - y, 1, 1);
        g.drawRect(xc - x, yc - y, 1, 1);
        g.drawRect(xc + y, yc + x, 1, 1);
        g.drawRect(xc - y, yc + x, 1, 1);
        g.drawRect(xc + y, yc - x, 1, 1);
        g.drawRect(xc - y, yc - x, 1, 1);
    }

    void CircleMidPoint(Point p1, Point p2) {
        int x, y, p, xc = p1.x, yc = p1.y;
        int r = (int) Math.sqrt(((p2.x - p1.x) * (p2.x - p1.x)) + ((p2.y - p1.y) * (p2.y - p1.y)));
        Graphics g = this.getGraphics();
        x = 0;
        y = r;
        p = 1 - r;
        PlotPoint(g, xc, yc, x, y);
        while (x < y) {
            x = x + 1;
            if (p < 0) {
                p = p + 2 * x + 1;
            } else {
                y = y - 1;
                p = p + 2 * (x - y) + 1;
            }
            PlotPoint(g, xc, yc, x, y);
        }
    }

    public void Elipse2(Point p1, Point p2) {
        Graphics g = this.getGraphics();
        g.setColor(Color.red);
        int an = (int) Math.sqrt(((p2.x - p1.x) * (p2.x - p1.x)) + ((p2.y - p1.y) * (p2.y - p1.y)));
        g.drawOval(p1.x, p1.y, an * 2, an);
    }

    public void triangulo(Point p1, Point p2, Point p3) {
        lineFast(p1.x, p1.y, p2.x, p2.y, Color.red);
        lineFast(p1.x, p1.y, p3.x, p3.y, Color.red);
        lineFast(p2.x, p2.y, p3.x, p3.y, Color.red);
        Graphics g = this.getGraphics();
        g.setColor(Color.red);
        int x[] = {p1.x, p2.x, p3.x};
        int y[] = {p1.y, p2.y, p3.y};
        g.fillPolygon(x, y, 3);
    }

    @Override
    public void update(Graphics g) {
        paint(g);

    }

    @Override
    public void paint(Graphics g) {
        if (firstTime) {
            firstTime = false;
            super.paint(g);
        }

        Image output = raster.toImage(this);
        g.drawImage(output, 0, 0, this);
    }

    public void clear() {
        int s = raster.size();
        for (int i = 0; i < s; i++) {
            raster.pixel[i] ^= 0x00ffffff;
        }
        repaint();
        return;
    }

    private void dibujarLinea(Point _p1, Point _p2, Color color) {
        lineFast(_p1.x, _p1.y, _p2.x, _p2.y, color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiniCad");
        setResizable(false);
        setSize(new java.awt.Dimension(640, 480));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        switch (op) {
            case 1:
                if (!bDibujar) {
                    p1.x = evt.getX();
                    p1.y = evt.getY();
                    bDibujar = true;
                } else {
                    p2.x = evt.getX();
                    p2.y = evt.getY();
                    dibujarLinea(p1, p2, Color.red);
                    bDibujar = false;
                }   break;
            case 2:
                if (!bDibujar) {
                    p1.x = evt.getX();
                    p1.y = evt.getY();
                    bDibujar = true;
                } else {
                    p2.x = evt.getX();
                    p2.y = evt.getY();
                    CircleMidPoint(p1, p2);
                    bDibujar = false;
                }   break;
            case 3:
                if (!bDibujar) {
                    p1.x = evt.getX();
                    p1.y = evt.getY();
                    bDibujar = true;
                } else {
                    p2.x = evt.getX();
                    p2.y = evt.getY();
                    Elipse2(p1, p2);
                    bDibujar = false;
                }   break;
            case 4:
                if (!bDibujar && !bDibujar2) {
                    p1.x = evt.getX();
                    p1.y = evt.getY();
                    bDibujar = true;
                } else if (bDibujar && !bDibujar2) {
                    p2.x = evt.getX();
                    p2.y = evt.getY();
                    bDibujar2 = true;
                } else if (bDibujar && bDibujar2) {
                    p3.x = evt.getX();
                    p3.y = evt.getY();
                    triangulo(p1, p2, p3);
                    bDibujar = bDibujar2 = false;
                }   break;
            default:
                break;
        }
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizarraC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizarraC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizarraC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizarraC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizarraC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
